#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#Set the build environment
env:
  - SOURCEMOD=1.7.2

#And compile!
before_script:
  - SMFILE="sourcemod-$SOURCEMOD-linux.tar.gz"
  - wget http://www.gsptalk.com/mirror/sourcemod/$SMFILE -O $SMFILE
  - tar -xzf $SMFILE
  - mv scripting/donormenu.sp addons/sourcemod/scripting/
  - cd addons/sourcemod/scripting/
  - wget https://bitbucket.org/GoD_Tony/updater/raw/53ebb3e27e5a43bc46dc52dc0de76ac2fb48cd9e/include/updater.inc -O include/updater.inc
  - chmod +x spcomp

script:
  - ./compile.sh donormenu.sp